### ISSUE TITLE
openapi.yaml is invalid according to openapi-generator

### ISSUE THREAD

**Issue by aranw** [thisisbud/bud-public-developer-resources#41]
While following the documentation [here](https://docs.thisisbud.com/docs/openapi-spec-and-libraries) I got the following errors and warnings 

```
> openapi-generator generate -i openapi.yaml -g go -o generated
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/TimezoneIdentifier
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/TimezoneIdentifier
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/DateTimeISO8601
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/DateTimeISO8601
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/DateTimeISO8601
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/DateTimeISO8601
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/DateTimeISO8601
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/DateTimeISO8601
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/DateTimeISO8601
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/DateTimeISO8601
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/TimezoneIdentifier
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/TimezoneIdentifier
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/PaymentServices
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/PaymentServices
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/CategoryTotal
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/schemas/CategoryTotal
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 6, Warning count: 2
Errors:
	-attribute components.schemas.PostalAddress.items is missing
	-components.schemas.Schema name Revoke Task Metadata doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-components.schemas.Schema name Updated Customer Context doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-components.schemas.Schema name Revoke Task Data doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.ComponentParameterSpec.items is missing
	-attribute components.schemas.ListAccountsV2Response_metatdata_parameters.items is missing
Warnings:
	-attribute components.schemas.PostalAddress.items is missing
	-components.schemas.Schema name Revoke Task Metadata doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-components.schemas.Schema name Updated Customer Context doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-components.schemas.Schema name Revoke Task Data doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.ComponentParameterSpec.items is missing
	-attribute components.schemas.ListAccountsV2Response_metatdata_parameters.items is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:668)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:695)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:503)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Comment by daveokeeffe** [comment]
I got the same result when trying to generate the typescript-node client.  The [node OpenAPI implementation](https://www.npmjs.com/package/api) also fails when generating the client library, it fails with the error Token "schemas" does not exist.  As far as I can tell, this openapi node implementation is the one shown in the example docs [here](https://docs.thisisbud.com/reference/oauth_token_post)

```bash
npm install api --save
```

```typescript
const sdk = require('api')('@bud-testing/v0.6.0#1iwehiliipz97c');

sdk.oauth_token_post({grant_type: 'refresh_token'})
  .then(({ data }) => console.log(data))
  .catch(err => console.error(err));
```

There's other issues where some names are badly formatted, like 'Revoke Task Metadata' instead of 'RevokeTaskMetadata'.  I can fix these in the openapi.yml, but that doesn't solve the missing schemas issue.

**Comment by tadasminiotasbud** [comment]
@aranw @daveokeeffe apologies for the delay. OpenAPI yaml is now valid and we have improved checks internally to ensure it stays valid. Please don't hesitate to open a support ticket if you encounter any issues using it.
